apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name_deploy }}
  labels:
  {{- range .Values.labels }}
    app: {{ . | quote }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bakehouse
  template:
    metadata:
      labels:
      {{- range .Values.labels }}
        app: {{ . | quote }}
      {{- end }}
    spec:
      containers:
      - image: {{ .Values.image_deploy }}
        name: {{ .Values.name_container }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:                                                                      