apiVersion: v1
kind: Service
metadata:
  labels:
  {{- range .Values.labels }}
    app: {{ . | quote }}
  {{- end }}
  name: {{ .Values.nameSvc }}
spec:
  ports:
  - name: {{ .Values.portName }}
    port: {{ .Values.port }}
    protocol: {{ .Values.protocol }}
    targetPort: {{ .Values.targetPort }}
    nodePort: {{ .Values.nodePort }}
  selector:
    app: bakehouse
  type: {{ .Values.type_svc }}
status:
  loadBalancer: